### PR TITLE
Editing README.md

### PR DESCRIPTION
**Pull request by mcdoash**
Added some basic info and things people can do before next year.

### CODE REVIEW

**Comment by Fay-Z** [comment]
Here are some more ideas
a link to most basic programming exercises http://www.codeabbey.com/index/task_list
1. First meeting: people intested in it and the average programming experiences of people 
2. Introductory information session: video - https://code.org/
Suggestions: Decide a big project that our club wish to accomplish at the end of the year
Examples: A mobile app(Android project), a website, a game
Trip to hackathon 
For students who are above 10 years old or have more experience I would suggest introducing them to MIT App Inventor, Codecademy and Khan Academy. All include tutorials and support resources. With MIT APP Inventor students can build Android apps in a drag and drop environment that is similar to Scratch. With Codecademy and Khan Academy there are a range of step by step interactive tutorials that teach some of the most commonly used programming languages.
MIT App Inventor - http://appinventor.mit.edu/explore/
Codecademy - https://www.codecademy.com/learn/all
Khan Academy - https://www.khanacademy.org/

**what do you like to do?**

**Comment by mcdoash** [comment]
@Fay-Z Regarding your comment: do you wish to add those points to the README.md or ClubInfo program, or were they simply ideas? All of the ideas are very interesting and we should definitely discuss them when we get together after exams.

**Comment by Fay-Z** [comment]
They are just some simple ideas, and also a plan for how we start the first
few meeting. We can decide later on the the summer. I was thinking we can
let them watch an inspiring video first, and give them an idea of the final
project we wish to finish at the idea so they will get excited about it.
Say if we want to aim for a Mobil app. During the summer, We can learn app
development together either by studying on a good website or find a class
to join.

**Comment by mcdoash** [comment]
@Fay-Z Sounds good! When are you available to meet up? Any time after Monday works for me.

**Comment by Fay-Z** [comment]
Sorry, I might not be able to meet on Mondays and Tuesdays . Other days
after school work.

**Pull request merged**
